export {
  DynamodbProvider,
  type CreateParams,
  type DeleteParams,
  type UpdateParams,
  type ListOptions,
  type QueryParams,
  type QueryConfigParams,
  type QueryResult,
  type TransactionParams,
  type DBSet,
  type BatchCreateParams,
  type BatchCreateResult,
  type BatchDeleteParams,
  type BatchDeleteResult,
  type BatchMutateParams,
  type BatchMutateResult,
} from './provider';

export {
  SingleTable,
  type SingleTableConfig,
  type SingleTableTransactionParams,
  type FromCollection,
  type FromEntity,
  type GetCollectionType,
  type GetCollectionParams,
  type GetCollectionResult,
  type ExtractTableConfig,
  type AnyEntity,
  type AnyCollection,
  type GetEntityParams,
  type UpdateEntityParams,
  type CreateEntityParams,
} from './singleTable';
